### ISSUE TITLE
[Bug] Headers inside of tab contents flickering

### ISSUE THREAD

**Issue by brcdev** [jhildenbiddle/docsify-tabs#27] opened 2020-07-07 13:43 UTC
Hello,

We've experienced a bug with tab switching - when there's an opening heading inside of a tab and you switch tabs, the heading is going to flicker. 

**Video showing the issue**: https://streamable.com/zbilpc
**Browsers used:** Firefox 70.0, Chromium 76.0.3809.100
**How to reproduce:** Put a heading inside of a tab (as its first content), switch tabs and notice the heading flickering

We also prepared a repo allowing you reproduce it easily - you can just clone it and run: https://github.com/brcdev/docsify-tabs-bug-demo

Thank you,
Emil

**Comment by PengXing** [comment] 2020-07-16 03:28
I have encountered the same issue.

**Comment by jhildenbiddle** [comment] 2020-11-03 21:50
Hi @brcdev --

Apologies for the *very* slow response on this.

I'm not seeing this behavior on [docsify-tabs website](https://jhildenbiddle.github.io/docsify-tabs/) which has headings in under "Tab B" and "Tab C" of the "Demo" section. I'm also not seeing it on a local site using the markdown in the repo linked above. Both were tested in Chrome 86, Firefox 82, and Safari 14 on macOS 10.15.7.

Perhaps the issue has been resolved in later versions of Chrome? If you're still seeing the issue, let me know and we'll investigate further.

Closing for now since I was unable to reproduce the issue, but I'm happy to reopen if needed.

Thanks!

**Comment by fauxpark** [comment] 2020-12-27 04:48
I am also able to reproduce this locally using the above test repo, on Firefox 84, Chrome 87, Edge 87 and Safari 14, on both Windows 10 and macOS 11.

**Comment by fauxpark** [comment] 2020-12-27 07:32
It seems the bug is present when the theme is set to any of the default docsify themes, and disappears when set to any of the docsify-themeable ones.

**Comment by jhildenbiddle** [comment] 2022-09-10 14:47
This issue has been fixed. I will push an update with the change later today. If you are loading docsify-tabs via CDN, it typically takes a day or so for jsdelivr to update their redirects to the latest version.

For those who may be curious what caused the bug, consider how inactive content is hidden:

https://github.com/jhildenbiddle/docsify-tabs/blob/1c608426f1cff21ddaf9dbaeb67c72f932b1d8e9/src/scss/style.scss#L35-L39

As others have pointed out, hiding/showing this content using `display: [block|none]` is easier and it does solve the problem for basic markdown content. The reason the method of shown above is used is so that hidden tab content has dimensions which is often necessary for content that is initialized via JavaScript such as embeds from places like CodePen, CodeSandbox, etc.

Here is the cause of the inactive content flicker:

https://github.com/jhildenbiddle/docsify-tabs/blob/1c608426f1cff21ddaf9dbaeb67c72f932b1d8e9/src/scss/style.scss#L76-L77

The bug was caused by the fact that `padding` is visible even when the `height` of a container is set to `0`. The fix was to apply padding only to the active tab content:

```css
.docsify-tabs__tab--active + .docsify-tabs__content {
    padding: var(--docsifytabs-content-padding);
}
```

Apologies for the slow turnaround on this. I somehow missed @fauxpark's comment where he mentioned the issue only being present when using doscify's default themes (like `vue.css`). Knowing this is what allowed me to reproduce and fix the bug, so thank you @fauxpark.

**Closed by jhildenbiddle** 2022-09-10 14:47 UTC
Labels: question
