### ISSUE TITLE
After [filename](README.md ':include'), the docsify-tabs plugin in README.md fails

### ISSUE THREAD

**Issue by zhangkaiqiu** [jhildenbiddle/docsify-tabs#53] opened 2023-07-04 08:38 UTC
Please see here for a detailed description
https://github.com/docsifyjs/docsify/issues/2000

**Comment by jhildenbiddle** [comment] 2024-02-15 22:55
Closing this issue as duplicate of issue found in docsify repo.

**Closed by jhildenbiddle** 2024-02-15 22:55 UTC
Labels: duplicate
