### ISSUE TITLE
!BUG - TABS bug at the bottom of the page

### ISSUE THREAD

**Issue by phuongbag** [jhildenbiddle/docsify-tabs#18] opened 2020-03-04 19:35 UTC
If u put the tabs at the bottom of the page it will stuck hard and didnt create scroll bar. (easiest way to see is using a phone)
I am using .md

e.g: http://neetvn.net/#/species/casau

For now i use tag right after it to make it move down. or else it will stuck

**Comment by jhildenbiddle** [comment] 2020-03-05 03:16
Hey @phuongbag --

I don't see tabs on the the page linked above. I am see no issues placing tabs as the last item in a markdown file on a desktop (Chrome) or mobile (iOS Safari) browser.

Closing due to inability to reproduce. I am happy to reopen if/when the issue can be reproduced.

**Closed by jhildenbiddle** 2020-03-05 03:16 UTC
Labels: question

**Comment by phuongbag** [comment] 2020-03-10 02:10
I was removed it for few reason, sorry.

Problem is I run the website with tabs plugin and it will have a bug that will not create a scroll bar. There are no bug in the console and I am using chrome to open it

It make all the Markdown table stuck. Here is the image i run on local host.https://imgur.com/a/GRTbqkH

**Comment by phuongbag** [comment] 2020-03-10 02:11
U can try this code to test. https://hastebin.com/dewobogepe.md
